version: "3.8"

services:
  web:
    container_name: backend
    build:
      context: .
      # Correct the path to your Dockerfile
      dockerfile: Dockerfile
    ports:
      - 7789:7789
    # Important to bind/mount your codebase dir to /app dir for live reload
    volumes:
      - ./:/app

  postgresql:
    container_name: go-client-postgres
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: pw
    ports:
      - '5433:5432'